version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx
    ports:
      - "8554:8554"   # RTSP port (host->container)
      - "8888:8888"   # HTTP port for dashboard (host->container)
    restart: always
    environment:
      - MTX_LOGLEVEL=info

  vehicle_counter:
    image: rickyindrag/vehicle-counter-rickyig:latest
    depends_on:
      - mediamtx
    volumes:
      - ./models:/app/models
      - ./input_video:/app/input_video
      - ./coco.names:/app/coco.names
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      python vehicle_counter.py
      --rtsp_url rtsp://mediamtx:8554/mystream
